Fixed segfault caused by empty array in CMDB class specification
Now an error message is emitted instead, when array is empty:

```
   error: Empty class specification '[]' in CMDB data not allowed, only '["any::"]'
```

Also added an error message when array contains more than one element:

```
   error: Too many elements in class specification in CMDB data, only '["any::"]' allowed
```

And the old error message is now only emitted when array contains one
element that is not "any::":

```
   error: Invalid class specification '["linux::"]' in CMDB data, only '["any::"]' allowed
```

Ticket: CFE-4145
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 55bb5d4ac2d923466e414a9a7a377199c6121390)
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>