Fixed issue when removing comments from files in various policy functions
This should also fix many erroneous occurences of the following error message:

```
   error: Comment regex '\s*#[^\n]*' was irreconcilable reading input 'test.txt' probably because it legally matches nothing
```

(A warning can still appear if a comment regex actually matches nothing).

Also made this comment removing logic faster.

Affected functions include:

* readstringlist()
* readintlist()
* readreallist()
* peers()
* peerleader()
* peerleaders()
* data_readstringarray()
* data_readstringarrayidx()
* data_expand()
* readstringarray()
* readstringarrayidx()
* readintarray()
* readrealarray()
* parsestringarray()
* parsestringarrayidx()
* parseintarray()
* parserealarray()

Changelog: Commit
Ticket: CFE-3188 ENT-5019
Signed-off-by: Ole Herman Schumacher Elgesem <ole@northern.tech>
(cherry picked from commit 19015cde5246e5f68fe45fad8091166b1c723c42)